# yml配置文件语法
## 1.key:value k-v结构 ":"；连接
## 2.yml配置文件有层级关系
## 3.yml配置文件注意缩进
## 4.yml文件支持中文，内部编码是utf-8
#为环境定义名称
spring:
  profiles:
    active: test
server:
  port: 8080
  #项目缺省值
  servlet:
    context-path: /
#在配置文件中添加属性和属性值
jdbc:
  username: root
  password: root
##配置文件的分割
---
spring:
  profiles:
    active: prod
server:
  port: 80
  #项目缺省值
  servlet:
    context-path: /
#在配置文件中添加属性和属性值
jdbc:
  username: cn.tedu
  password: tarena